name: beep_operator
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  responsive_framework: ^1.0.0
  get: ^4.6.5
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Black.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans-Light.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf